// This file is automatically generated. Do not edit it directly.
import { createClient, type Session } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}


function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      // Troca o ?code= do retorno do Google por uma sessão automaticamente.
      detectSessionInUrl: true,
      flowType: 'pkce',
    }
  });
}

/**
 * Sessão atual, esperando a troca do código do OAuth quando ela está em curso.
 *
 * No retorno do Google a URL chega com `?code=...` e o supabase-js ainda está
 * trocando esse código por uma sessão. Perguntar `getSession()` nesse instante
 * responde "sem sessão" — era isso que jogava o usuário de volta para a tela de
 * login logo depois de entrar. Aqui, se a URL indica um retorno de login, a
 * gente aguarda o `onAuthStateChange` em vez de concluir que não há login.
 */
export async function getSettledSession() {
  const { data } = await supabase.auth.getSession();
  if (data.session) return data.session;

  const url = typeof window !== 'undefined' ? window.location.href : '';
  const isAuthCallback = /[?&#](code|access_token|error_description)=/.test(url);
  if (!isAuthCallback) return null;

  return new Promise<Session | null>((resolve) => {
    let done = false;
    const finish = (session: Session | null) => {
      if (done) return;
      done = true;
      clearTimeout(timer);
      subscription?.unsubscribe();
      resolve(session);
    };
    const timer = setTimeout(() => finish(null), 8000);
    const { data: sub } = supabase.auth.onAuthStateChange((_event, session) => {
      if (session) finish(session);
    });
    const subscription = sub.subscription;
    // A troca pode ter terminado entre o getSession e o subscribe.
    supabase.auth.getSession().then(({ data: d }) => {
      if (d.session) finish(d.session);
    });
  });
}

/**
 * Estado de acesso do usuário logado: se é admin e se a conta foi aprovada.
 * Admin sempre passa. Se a coluna `approved` ainda não existir no banco
 * (migração não aplicada), trata como aprovado para não trancar ninguém.
 */
export async function getAccessState(userId: string): Promise<{ isAdmin: boolean; approved: boolean }> {
  const [{ data: adminRow }, { data: prof, error }] = await Promise.all([
    supabase.from("user_roles").select("role").eq("user_id", userId).eq("role", "admin").maybeSingle(),
    supabase.from("profiles").select("approved").eq("id", userId).maybeSingle(),
  ]);
  const isAdmin = !!adminRow;
  if (error && /approved/.test(error.message)) return { isAdmin, approved: true };
  const approved = (prof as any)?.approved ?? false;
  return { isAdmin, approved: isAdmin || approved };
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

